#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost # eureka服务端的实力名称
#  client:
#    registerWithEureka: false  # false表示自己不需要向注册中心注册自己
#    fetchRegistry: false  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/  # 集群版
#
#spring:
#  application:
#    name: eurka-server

  spring:
  application:
    name: eureka
  profiles:
    active: server1
