

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

spring:
  cloud:
    config:
      label: master
      profile: dev  # 配置版本 开发环境
      uri: http://localhost:8888/  # 配置服务器的地址
      name: service-hi
      retry:   # 配置重试，默认是重试6次，最初是延迟1s再次重试，如果再失败，则延迟1.1*1s、1.1*1.1*1s、 可以使用这个配置
        initial-interval: 2000
        # 最多重试次数
        max-attempts: 6
        # 最大重试间隔
        max-interval: 4000
        # 每次重试时间是之前的倍数
        multiplier: 1.2


