
server:
  post: 8888
spring:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xiaoqi54321/warfarin.git
          basedir: F:\idea2019\server-core\warfarin\shared
          force-pull: true
          username: tmh1128@foxmail.com
          passeord: tianhao0907
        searchPaths: respo


eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/
