
#spring.application.name=config-server
#server.port=8888
#
#
#spring.cloud.config.server.git.uri=https://github.com/xiaoqi54321/warfarin.git
#spring.cloud.config.server.git.searchPaths=respo
#spring.cloud.config.label=master
#spring.cloud.config.server.git.basedir=F:\idea2019\server-core\warfarin\shared
#spring.cloud.config.server.git.force-pull=true
#spring.cloud.config.server.git.username=tmh1128@foxmail.com
#spring.cloud.config.server.git.password=tianhao0907

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xiaoqi54321/warfarin.git
          basedir: F:\idea2019\server-core\warfarin\shared
          force-pull: true
          username: tmh1128@foxmail.com
          passeord: tianhao0907
        searchPaths: respo
server:
  post: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-serve-01:8761/eureka/
